export XDG_CONFIG_HOME=$HOME/.config

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export DOTNET_TOOLS_PATH=$HOME/.dotnet/tools
export PATH=$PATH:$DOTNET_TOOLS_PATH

export CARGO_PATH=$HOME/.cargo/bin
export PATH=$PATH:$CARGO_PATH

export NPM_PATH=`npm prefix --location=global`/bin
export PATH=$PATH:$NPM_PATH

setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt HIST_FCNTL_LOCK
setopt AUTO_CD

setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt HIST_FCNTL_LOCK
setopt AUTO_CD

bindkey -v

# Aliases
alias ls='ls -G'
alias l='ls'

alias cls='clear;ls'

alias reload="source $HOME/.zshrc"

# fzf
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# direnv
eval "$(direnv hook zsh)"

# starship
eval "$(starship init zsh)"
