if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

eval "$(direnv hook zsh)"

export XDG_CONFIG_HOME=$HOME/.config

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export DOTNET_TOOLS_PATH=$HOME/.dotnet/tools
export PATH=$PATH:$DOTNET_TOOLS_PATH

export CARGO_PATH=$HOME/.cargo/bin
export PATH=$PATH:$CARGO_PATH

export NPM_PATH=`npm prefix --location=global`/bin
export PATH=$PATH:$NPM_PATH

# Aliases
alias cls='clear;ls'

alias vim='nvim'

alias zshrc="nvim $HOME/.zshrc"
alias nvimrc="nvim $XDG_CONFIG_HOME/nvim/init.lua"
alias plugins="nvim $XDG_CONFIG_HOME/nvim/lua/plugins.lua"

alias reload="source $HOME/.zshrc"

export RLWRAP_COMMAND=`which rlwrap`
alias ocaml="$RLWRAP_COMMAND ocaml"
